import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Navbar = () => {
  const user = useUser();
  return (
    <nav className="absolute flex w-full flex-wrap items-center justify-between p-6">
      <div className="mr-6 flex flex-shrink-0 items-center text-white">
        <span className="text-xl font-semibold tracking-tight">
          Meso Predictions
        </span>
      </div>
      <div className="block lg:hidden">
        <button className="flex items-center rounded border border-gray-600 px-3 py-2 text-gray-500 hover:border-white hover:text-white">
          <svg
            className="h-3 w-3 fill-current"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
          </svg>
        </button>
      </div>
      <div className="block w-full flex-grow lg:flex lg:w-auto lg:items-center">
        <div className="text-sm lg:flex-grow">
          <Link href="/">
            <p className="mt-4 mr-4 block font-semibold text-gray-200 hover:text-white lg:mt-0 lg:inline-block">
              Home
            </p>
          </Link>
          <Link href="/about">
            <p className="mt-4 mr-4 block font-semibold text-gray-200 hover:text-white lg:mt-0 lg:inline-block">
              About
            </p>
          </Link>
          <Link href="/contact">
            <p className="mt-4 mr-4 block font-semibold text-gray-200 hover:text-white lg:mt-0 lg:inline-block">
              Contact
            </p>
          </Link>
        </div>
        <div>
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </div>
      </div>
    </nav>
  );
};

const Home: NextPage = () => {
  const allPosts = api.posts.getAll.useQuery();
  console.log(allPosts);

  const user = useUser();
  return (
    <>
      <Head>
        <title>Meso Predictions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#8D7096] to-[#B9A0AF]">
        <h1 className="font-mono text-4xl font-semibold text-white">
          Hello, Welcome to Meso Predictions.
        </h1>
      </main>
    </>
  );
};

export default Home;
